# Site settings
title: Jonathan Weiss
email: jdweiss@stanford.edu
url: weiss-jonathan.github.io
description: Jonathan Weiss' Website #"Write an awesome description for your new site here. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "jonathan, weiss, phd, stanford, 3d printing, tissue engineering"
skills: "3D Printing - Tissue Engineering - Education"
meta_author: Weiss Jonathan


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F0F0F0 #80B3FF
  primary-rgb: "240,240,240" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  #copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jonathan-weiss/
  - title: spotify
    url: https://open.spotify.com/artist/1bSYDuBbxYOaH67TOzqy5X
  - title: google-scholar
    url: https://scholar.google.com/citations?user=OaLCWBQAAAAJ
    
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  #- title: github
  #  url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  #- line: 3481 Melrose Place
  - line: Stanford, CA 94305

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
